# This configuration creates one ADS instance, which can be used to create multiple "child" instances.
# This is a good choice if you want to run multiple game servers, even of different types.

services:
  amp:
    image: mitchtalmadge/amp-dockerized:latest
    mac_address: 02:42:AC:69:1A:63 # Please see the README about this field.
    ports:
      - 8080:8080
    volumes:
      - ./ampdata:/home/amp/.ampdata
    environment:
      - "UID=1000" # Change according to which user on the host will own the ampdata volume.
      - "GID=1000"
      - "TZ=Europe/Budapest" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - "MODULE=ADS"
      - "LICENCE=${AMP_LICENCE}"
    restart: unless-stopped
