# This has minor adjustments to get working on a Portaienr cluster
---
version: "3.6" # this must be 3.6
services:
  amp:
    image: mitchtalmadge/amp-dockerized:latest
    mac_address: 02:42:AC:XX:XX:XX #generated
    container_name: amp
    environment:
      - UID=1000 # change to your portainer uid
      - GID=1000 # change to your portainer gid
      - TZ=Etc/UTC
      - LICENCE=<licence key>
      - MODULE=ADS # only tested with ADS
    volumes:
      - /etc/amp/:/home/amp/.ampdata # needs to be ownable by portainer uid
    ports:
      - 8080:8080
      - 5678-5680:5678-5680/udp # valheim - amp defaults to 2456-2458
    restart: unless-stopped
