name: "Auto Deploy Staging Branches"

on:
  push:
    branches:
      - "staging*"
    paths:
      - Dockerfile
      - .dockerignore
      - entrypoint/**
      - .github/workflows/**.yml

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/heads/staging') }}
    uses: MitchTalmadge/AMP-dockerized/.github/workflows/build.yml@staging
    with:
      for_deploy: true

  deploy:
    needs: [build]
    uses: MitchTalmadge/AMP-dockerized/.github/workflows/deploy-staging.yml@staging
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
